### ISSUE TITLE
Forget some required arguments?

### ISSUE THREAD

**Issue by oishimilk** [Meijo-TasakiLab/AlexNet#1]
Hi, there.

When we do (we forget `-v` and `-e` options):
```sh
$ AlexNet/alexnet.py -t path/to/dataset
````

we get an error like:
```
Traceback (most recent call last):
  File "AlexNet/alexnet.py", line 142, in <module>
    main(args)
  File "AlexNet/alexnet.py", line 62, in main
    config=conf, root=args.test)
  File "/content/AlexNet/lib/dataset.py", line 161, in __init__
    max_samples = max(self.class_samples.values())
ValueError: max() arg is an empty sequence
```

In my opinion, it might make users confused. I suggest you [mark these arguments as *required*.](https://docs.python.org/ja/3/library/argparse.html#required)

How about adding `required=True` at the end of `PARSER.add_argument`? For example,
```python
PARSER.add_argument('-t', '--train', default=None, type=str, metavar='PATH', help='学習用データセットのディレクトリのパスを入力します．テストのみ行う場合は不要です．(例: "./dataset_train")', required=True)
PARSER.add_argument('-v', '--val', default=None, type=str, metavar='PATH', help='確認用データセットのディレクトリのパスを入力します．(例: "./dataset_val")', required=True)
PARSER.add_argument('-e', '--test', default="./dataset_test", type=str, metavar='PATH', help='テスト用データセットのディレクトリのパスを入力します．(例: "./dataset_test")', required=True)
```

Thanks.

**Comment by shikishima-TasakiLab** [comment]
[commit 26c4cbc
](https://github.com/Meijo-TasakiLab/AlexNet/commit/26c4cbc0debbe22bfc85e78954107169ee436d0e)

I fixed the following:

- before
    ```python
    PARSER.add_argument('-e', '--test', default="./dataset_test", type=str, metavar='PATH', help='テスト用データセットのディレクトリのパスを入力します．(例: "./dataset_test")')
    ```
- after
    ```python
    PARSER.add_argument('-e', '--test', default=None, type=str, metavar='PATH', required=True, help='テスト用データセットのディレクトリのパスを入力します．(例: "./dataset_test")')
    ```

This error was due to missing test data in the default test data directory.

**Comment by oishimilk** [comment]
Hi, @shikishima-TasakiLab .
Thank you for fixing the code. I'll close the issue.
